{
 "title": "Spark Cluster metrics Demo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cluster general",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free cores",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(metrics_worker_coresFree_Value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free memory",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(metrics_worker_memFree_MB_Value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free memory in cluster",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "sum(metrics_worker_memFree_MB_Value)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Workers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "metrics_master_workers_Value", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Workers alive",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metrics_master_aliveWorkers_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "sum(metrics_executor_activeTasks)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(metrics_executor_failedTasks_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workers cores used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (metrics_worker_coresUsed_Value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workers memory used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (metrics_worker_memUsed_MB_Number)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metrics_master_apps_Number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waiting apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_waitingApps_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shuffle write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum by(application_name) (metrics_executor_totalShuffleWrite_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hive Metastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Partitions fetched Hive Metastore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "metrics_app_20240728171930_0004_driver_HiveExternalCatalog_partitionsFetched_Count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hive Metastore calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "metrics_HiveExternalCatalog_hiveClientCalls_Count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}